#!/bin/bash
#
#arvu paarsuse kontroll
#
#kasuta kasurealised parameetrid arvude sisestamiseks
#kontrollime, kas parameetrid arv on 1
#kui nii ei ole
if [ $# -ne 1 ]; then
echo "kasutajajuhend: "
echo "$0 arv"
echo "Naiteks: $0 -5"
else
arv=$1
#if lause algus
# kontrollime, kas arv on paaris
if [ $arv -gt 0 ]; then
#arv on positiivne
echo "$arv on positiivne"
#muidu kui arv on vaiksem kui 0
elif [ $arv -lt 0 ]; then
#arv on negatiivne
echo "$arv on negatiivne"
#kui ei ole suurem ega vaiksem kui 0
else
echo "$arv on neutraalne"
#if lause lõpp
fi
echo "programmi lopp"
fi
