#!/bin/bash
#
# täisnurkne kolmnurk
#
#loome muutuja nii, et kasutaja sisestavad väärtused ise
echo -n "sisesta a külje vaartus: "
read a # sellega tekib  a muutuja, mille sisse on salvestatud kasutaja sisestatud vaartus
echo -n "sisesta b külje vaartus: "
read b
# arvutused
# c = sqrt(a^2 + b^2)
c=$(echo "scale=2;sqrt($a^2 + $b^2)" | bc) # bc arvutused
echo "c = $c"
