#!/bin/bash
#
#failist info lugemine
#
while read rida
do
  # Loeme iga rida : märkidega
  # ja teisendame selle nii, et rida oleks tühikuga
  rida=$(echo $rida | sed 's/:/ /g')
  # tühikutega rida on lihtne sõnadeks lõigata for tsükliga
  for sona in $rida
  do
  echo $sona # trükime iga sõna välja
  done
done < fail
